//  ██╗    ██╗ █████╗ ██████╗ ██╗      ██████╗  ██████╗██╗  ██╗███████╗
//  ██║    ██║██╔══██╗██╔══██╗██║     ██╔═══██╗██╔════╝██║ ██╔╝██╔════╝
//  ██║ █╗ ██║███████║██████╔╝██║     ██║   ██║██║     █████╔╝ ███████╗
//  ██║███╗██║██╔══██║██╔══██╗██║     ██║   ██║██║     ██╔═██╗ ╚════██║
//  ╚███╔███╔╝██║  ██║██║  ██║███████╗╚██████╔╝╚██████╗██║  ██╗███████║
//   ╚══╝╚══╝ ╚═╝  ╚═╝╚═╝  ╚═╝╚══════╝ ╚═════╝  ╚═════╝╚═╝  ╚═╝╚══════╝
//                           TEAM 1507 WARLOCKS

package frc.robot;

// Java Standard Library
import java.util.function.Supplier;

// WPI / WPILib
import edu.wpi.first.math.geometry.Pose2d;
import edu.wpi.first.math.geometry.Rotation2d;
import edu.wpi.first.math.kinematics.ChassisSpeeds;
import edu.wpi.first.wpilibj.smartdashboard.SendableChooser;
import edu.wpi.first.wpilibj2.command.Command;
import edu.wpi.first.wpilibj2.command.Commands;
import edu.wpi.first.wpilibj2.command.button.CommandXboxController;
import edu.wpi.first.wpilibj2.command.button.RobotModeTriggers;
import edu.wpi.first.wpilibj.Filesystem;
import edu.wpi.first.wpilibj.RobotBase;

// Commands
import frc.robot.commands.atomic.*;
import frc.robot.commands.auto.routines.*;
import frc.robot.commands.coordinators.*;
import frc.robot.dashboard.DashboardManager;
// Subsystems
import frc.robot.subsystems.*;
// Localization
import frc.robot.localization.nodes.Nodes.*;
import frc.robot.localization.QuestNavController;

// IO Layer (Hardware Abstractions)
import frc.lib.io.agitator.*;
import frc.lib.io.feeder.*;
import frc.lib.io.hopper.*;
import frc.lib.io.intakearm.*;
import frc.lib.io.intakeroller.*;
import frc.lib.io.questnav.*;
import frc.lib.io.shooter.*;
import frc.lib.io.swerve.*;

// Hardware Config / Vendor Libraries
import frc.robot.generated.ctre.CommandSwerveDrivetrain;
import frc.robot.generated.ctre.TunerConstants;
import frc.lib.hardware.*;

// Core
import frc.lib.core.logging.Telemetry;
import frc.lib.core.shooterML.model.*;

// Framework
import frc.robot.framework.*;

// Constants
import frc.robot.Constants.*;

public class RobotContainer {

    // ==========================================================
    // Controllers
    // ==========================================================
    // Driver and operator controllers. Created once and used robot‑wide.
    private final CommandXboxController bottomDriver = new CommandXboxController(0);
    private final CommandXboxController topDriver = new CommandXboxController(1);

    // ==========================================================
    // Telemetry Logger
    // ==========================================================
    // Central AdvantageKit logger for structured telemetry.
    private final Telemetry logger = new Telemetry();

    // ==========================================================
    // Drive configuration
    // ==========================================================
    // CTRE Swerve drivetrain instance generated by Phoenix Tuner.
    private final CommandSwerveDrivetrain ctreDrivetrain =
        TunerConstants.createDrivetrain();

    // Default drive command (field‑relative swerve control).
    private Command defaultDriveCommand() {
        return swerve.run(() -> {
            double scale = bottomDriver.leftBumper().getAsBoolean() 
                ? kSwerve.kScale.CREEP 
                : kSwerve.kScale.NORMAL;

            double vx = -bottomDriver.getLeftY() * kSwerve.MAX_SPEED * scale;
            double vy = -bottomDriver.getLeftX() * kSwerve.MAX_SPEED * scale;
            double omega = -bottomDriver.getRightX() * kSwerve.MAX_ANGULAR_RATE * scale;

            swerve.drive(new ChassisSpeeds(vx, vy, omega));
        });
    }

    // ==========================================================
    // Subsystems (declared here, instantiated in constructor)
    // ==========================================================
    private final SwerveSubsystem swerve;

    // Shooter subsystems (Blue + Yellow)
    public final ShooterSubsystem shooterBLUsystem;
    public final ShooterSubsystem shooterYELsystem;
    private final Supplier<Pose2d> poseSupplier;
    private final ShooterModel shooterModelConfig;

    // Mechanisms
    public final AgitatorSubsystem agitatorSubsystem;
    public final FeederSubsystem feederBLUsystem;
    public final FeederSubsystem feederYELsystem;
    public final HopperSubsystem hopperSubsystem;
    public final IntakeArmSubsystem intakeArmSubsystem;
    public final IntakeRollerSubsystem intakeRollerSubsystem;

    // Vision system (PhotonVision)
    public final QuestNavController questNav;

    // ==========================================================
    // Records (group subsystems for autos, coordinators, dashboard)
    // ==========================================================
    private final SubsystemsRecord subsystemsRecord;
    private final CoordinatorRecord coordinatorRecord;
    private final LocalizationRecord localizationRecord;

    // ==========================================================
    // Autonomous chooser
    // ==========================================================
    private final SendableChooser<Command> autoChooser;

    // ==========================================================
    // Dashboard manager
    // ==========================================================
    private final DashboardManager dashboardManager;

    // ==========================================================
    // Robot Container Constructor
    // ==========================================================
    // Central wiring point for the entire robot. Subsystems, records,
    // vision, autos, and dashboard are all initialized here.
    public RobotContainer() {

        // -------------------------
        // Swerve
        // -------------------------
        // Swerve IO is created first so poseSupplier and vision can depend on it.
        swerve = new SwerveSubsystem(new SwerveIOReal(ctreDrivetrain));
        poseSupplier = swerve::getPose;

        // Load shooter ML model (shared by both shooters).
        shooterModelConfig =
            ModelLoader.load(
                Filesystem.getDeployDirectory().toPath().resolve("model.json").toString(), 
                poseSupplier);

        // -------------------------
        // Shooter IO + Subsystems
        // -------------------------
        ShooterIO shooterBLUIO =
            RobotBase.isReal()
                ? new ShooterIOReal(
                    ShooterHardware.BLU_ID,
                    kShooter.BLU_CONFIG,
                    ShooterHardware.BLU_DIO)
                : new ShooterIOSim(
                    kShooter.BLU_CONFIG,
                    kShooter.kSim.FLYWHEEL_MODEL,
                    ShooterHardware.BLU_RATIO);

        ShooterIO shooterYELIO =
            RobotBase.isReal()
                ? new ShooterIOReal(
                    ShooterHardware.YEL_ID,
                    kShooter.YEL_CONFIG,
                    ShooterHardware.YEL_DIO)
                : new ShooterIOSim(
                    kShooter.YEL_CONFIG,
                    kShooter.kSim.FLYWHEEL_MODEL,
                    ShooterHardware.YEL_RATIO);

        shooterBLUsystem =
            new ShooterSubsystem(
                shooterBLUIO,
                ShooterHardware.BLU_RATIO,
                ShooterHardware.ROBOT_TO_BLU_SHOOTER,
                shooterModelConfig,
                poseSupplier,
                Hub.CENTER,
                logger,
                "Shooter-BLU");

        shooterYELsystem =
            new ShooterSubsystem(
                shooterYELIO,
                ShooterHardware.YEL_RATIO,
                ShooterHardware.ROBOT_TO_YEL_SHOOTER,
                shooterModelConfig,
                poseSupplier,
                Hub.CENTER,
                logger,
                "Shooter-YEL");

        // -------------------------
        // Other subsystems
        // -------------------------
        agitatorSubsystem =
            new AgitatorSubsystem(
                new AgitatorIOReal(
                    AgitatorHardware.AGITATOR_ID, 
                    kAgitator.CONFIG));

        feederBLUsystem =
            new FeederSubsystem(
                new FeederIOReal(
                    FeederHardware.BLU_ID, 
                    kFeeder.BLU_CONFIG));

        feederYELsystem =
            new FeederSubsystem(
                new FeederIOReal(
                    FeederHardware.YEL_ID, 
                    kFeeder.YEL_CONFIG));

        hopperSubsystem =
            new HopperSubsystem(
                RobotBase.isReal()
                    ? new HopperIOReal(
                        HopperHardware.HOPPER_ID,
                        kHopper.CONFIG,
                        HopperHardware.RATIO,
                        HopperHardware.HOPPER_DIO)
                    : new HopperIOSim());

        intakeArmSubsystem =
            new IntakeArmSubsystem(
                RobotBase.isReal()
                    ? new IntakeArmIOReal(
                        IntakeArmHardware.BLU_ID, kIntake.kArm.BLU_CONFIG,
                        IntakeArmHardware.YEL_ID, kIntake.kArm.YEL_CONFIG,
                        IntakeArmHardware.RATIO)
                    : new IntakeArmIOSim());

        intakeRollerSubsystem =
            new IntakeRollerSubsystem(
                RobotBase.isReal()
                    ? new IntakeRollerIOReal(
                        IntakeRollerHardware.ROLLER_ID,
                        kIntake.kRoller.CONFIG)
                    : new IntakeRollerIOSim());

        // -------------------------
        // Vision
        // -------------------------
        questNav = new QuestNavController(swerve, new QuestNavSubsystem(new QuestNavIOReal()));

        // -------------------------
        // Records
        // -------------------------
        // Group subsystems into logical bundles for autos and coordinators.
        subsystemsRecord =
            new SubsystemsRecord(
                swerve,
                agitatorSubsystem,
                feederBLUsystem,
                feederYELsystem,
                hopperSubsystem,
                intakeArmSubsystem,
                intakeRollerSubsystem,
                shooterBLUsystem,
                shooterYELsystem,
                questNav);

        coordinatorRecord =
            new CoordinatorRecord(
                shooterYELsystem, shooterBLUsystem,
                feederYELsystem, feederBLUsystem,
                agitatorSubsystem, intakeRollerSubsystem);

        localizationRecord =
            new LocalizationRecord(swerve, questNav);

        autoChooser = new SendableChooser<>();

        dashboardManager =
            new DashboardManager(subsystemsRecord, localizationRecord, autoChooser);

        // Configure robot behavior.
        configureTelemetry();
        configureDefaultCommands();
        configureDriverControls();
        configureAutos();

        // Initialize dashboard layout.
        dashboardManager.initDashboard();
    }

    // ==========================================================
    // Default commands
    // ==========================================================
    // Default commands define idle behavior for each subsystem.
    private void configureDefaultCommands() {

        // Swerve default drive control
        swerve.setDefaultCommand(defaultDriveCommand());

        // Stop swerve when disabled
        RobotModeTriggers.disabled()
            .whileTrue(
                Commands.run(swerve::stop, swerve).ignoringDisable(true)
            );

        // Intake Arm manual control
        intakeArmSubsystem.setDefaultCommand(
            IntakeArmCommands.manualPower(intakeArmSubsystem, () -> topDriver.getLeftY())
        );

        // Hopper manual control
        hopperSubsystem.setDefaultCommand(
         HopperCommands.manualPower(hopperSubsystem, () -> topDriver.getRightY())
        );
    }

    // ==========================================================
    // Driver controls
    // ==========================================================
    // Declarative bindings for driver and operator controls.
    private void configureDriverControls() {

        // ----------------------------
        // Drive
        // ----------------------------
        bottomDriver.rightStick()
            .whileTrue(
                DriveCommands.maintainHeadingToTarget(
                    swerve,
                    shooterBLUsystem::getTargetPose,
                    () -> -bottomDriver.getLeftY() * kSwerve.MAX_SPEED,
                    () -> -bottomDriver.getLeftX() * kSwerve.MAX_SPEED));

        bottomDriver.x()
            .whileTrue(DriveCommands.lock(swerve));

        // ----------------------------
        // Intake
        // ----------------------------
        topDriver.rightTrigger(0.5)
            .onTrue(IntakeRollerCommands.incrementRollerDC(intakeRollerSubsystem));

        topDriver.leftTrigger(0.5)
            .onTrue(IntakeRollerCommands.lowRollerSpeed(intakeRollerSubsystem));

        bottomDriver.leftTrigger(0.5)
            .whileTrue(
                IntakeSequences.deployAndRun(
                    hopperSubsystem,
                    intakeArmSubsystem,
                    intakeRollerSubsystem))
            .onFalse(
                IntakeSequences.stow(
                    intakeArmSubsystem,
                    intakeRollerSubsystem));

        bottomDriver.b()
            .whileTrue(IntakeArmCommands.down(intakeArmSubsystem))
            .whileTrue(IntakeRollerCommands.outtake(intakeRollerSubsystem))
            .onFalse(IntakeRollerCommands.stop(intakeRollerSubsystem))
            .onFalse(IntakeArmCommands.up(intakeArmSubsystem));

        // ----------------------------
        // Shooting
        // ----------------------------
        bottomDriver.rightTrigger()
            .whileTrue(ShooterControllers.shootModelBased(
                coordinatorRecord,
                kAgitator.AGITATE_TO_SHOOTER_DUTY,
                kIntake.kRoller.DUTY_HIGH));

        bottomDriver.rightBumper()
            .whileTrue(ShooterControllers.shootFixedRPM(
                coordinatorRecord,
                kShooter.kRPM.LOB,
                kAgitator.AGITATE_TO_SHOOTER_DUTY,
                kIntake.kRoller.DUTY_HIGH));

        // ----------------------------
        // Agitator
        // ----------------------------
        topDriver.povUp().whileTrue(AgitatorCommands.toShooter(agitatorSubsystem));
        topDriver.povDown().whileTrue(AgitatorCommands.toIntake(agitatorSubsystem));

        // ----------------------------
        // Reset Gyro
        // ----------------------------
        bottomDriver.start().whileTrue(
            Commands.run(() -> questNav.requestPoseReset(
                new Pose2d(swerve.getPose().getTranslation(), new Rotation2d()))));

        //
        bottomDriver.back().whileTrue(
            Commands.run(() -> questNav.requestPoseReset(
                driverPoses.Blue.HUB)));
    }
    
    // ==========================================================
    // Telemetry
    // ==========================================================
    // Registers drivetrain telemetry with AdvantageKit.
    private void configureTelemetry() {
        ctreDrivetrain.registerTelemetry(logger::logDriveState);
    }

    // ==========================================================
    // Autos
    // ==========================================================
    // Autonomous routines built using subsystem and coordinator records.
    private void configureAutos() {

        autoChooser.setDefaultOption("Do Nothing", Commands.print("Doing nothing"));

        autoChooser.addOption(
            "Auto Subway 6 inch Right",
            AutoSubway6inchRight.build(subsystemsRecord, coordinatorRecord, kSwerve.MAX_SPEED * 0.8, kSwerve.MAX_ANGULAR_RATE));

        autoChooser.addOption(
            "Auto Subway 6 inch Right red",
            AutoSubway6InchRightRed.build(subsystemsRecord, coordinatorRecord, kSwerve.MAX_SPEED * 0.8, kSwerve.MAX_ANGULAR_RATE));

        autoChooser.addOption(
            "Auto Subway 6 inch Left Red",
            AutoSubway6InchLeftRed.build(subsystemsRecord, coordinatorRecord, kSwerve.MAX_SPEED * 0.8, kSwerve.MAX_ANGULAR_RATE));

        autoChooser.addOption(
            "Auto Subway 6 inch Left",
            AutoSubway6inchLeft.build(subsystemsRecord, coordinatorRecord, kSwerve.MAX_SPEED * 0.8, kSwerve.MAX_ANGULAR_RATE));

        autoChooser.addOption(
            "Auto Subway Footlong Right",
            AutoSubwayFootlongRight.build(subsystemsRecord, coordinatorRecord, kSwerve.MAX_SPEED * 1.0, kSwerve.MAX_ANGULAR_RATE));
        
        autoChooser.addOption(
            "Autoah Raymond",
            AutoahRaymond.build(subsystemsRecord, coordinatorRecord, kSwerve.MAX_SPEED * 0.5, kSwerve.MAX_ANGULAR_RATE));

        autoChooser.addOption(
            "Auto Human Player Q",
            AutoHumanPlayerQuest.build(subsystemsRecord, coordinatorRecord, kSwerve.MAX_SPEED * 0.5, kSwerve.MAX_ANGULAR_RATE));

        autoChooser.addOption(
            "Auto Double Subway",
            AutoDoubleSubway.build(subsystemsRecord, coordinatorRecord, kSwerve.MAX_SPEED * 0.8, kSwerve.MAX_ANGULAR_RATE));

        autoChooser.addOption(
            "Auto Subway 18 Inch Right Blue",
            AutoSubway18Inch.build(subsystemsRecord, coordinatorRecord, kSwerve.MAX_SPEED * 0.8, kSwerve.MAX_ANGULAR_RATE));
        
        autoChooser.addOption(
            "Auto Subway 18 Inch Right Red",
            AutoSubway18InchRightRed.build(subsystemsRecord, coordinatorRecord, kSwerve.MAX_SPEED * 0.8, kSwerve.MAX_ANGULAR_RATE));
        autoChooser.addOption(
            "Auto Subway 18 Inch left Blue",
            AutoSubway18InchLeftBlue.build(subsystemsRecord, coordinatorRecord, kSwerve.MAX_SPEED * 0.8, kSwerve.MAX_ANGULAR_RATE));
        autoChooser.addOption(
            "Auto Subway 18 Inch Left Red",
            AutoSubway18InchLeftRed.build(subsystemsRecord, coordinatorRecord, kSwerve.MAX_SPEED * 0.8, kSwerve.MAX_ANGULAR_RATE));

        autoChooser.addOption(
            "Auto Subway Around Hub",
            AutoSubwayAroundTheHub.build(subsystemsRecord, coordinatorRecord, kSwerve.MAX_SPEED * 0.8, kSwerve.MAX_ANGULAR_RATE));
    }

    public Command getAutonomousCommand() {
        return autoChooser.getSelected();
    }

    // ==========================================================
    // Dashboard access for Robot.java
    // ==========================================================
    // Called periodically from Robot.java to push dashboard updates.
    public void updateDashboard(){
        dashboardManager.updateInputs();
    }
}
